import * as vscode from 'vscode';
import * as path from 'path';
import { RuleInfo, SkillInfo, TargetPlatform } from './types';

/**
 * Workspace skill folder per platform:
 *   - Claude Code  -> {project}/.claude/skills
 *   - Antigravity  -> {project}/.agent/skills
 *   - Cursor       -> {project}/.cursor/skills
 */
export function getSkillsDir(projectPath: string, platform: TargetPlatform): string {
  switch (platform) {
    case 'antigravity':
      return path.join(projectPath, '.agent', 'skills');
    case 'cursor':
      return path.join(projectPath, '.cursor', 'skills');
    case 'claude-code':
    default:
      return path.join(projectPath, '.claude', 'skills');
  }
}

/**
 * Workspace rule folder per platform:
 *   - Claude Code  -> {project}/.claude/rules
 *   - Antigravity  -> {project}/.agents/rules
 *   - Cursor       -> {project}/.cursor/rules
 */
export function getRulesDir(projectPath: string, platform: TargetPlatform): string {
  switch (platform) {
    case 'antigravity':
      return path.join(projectPath, '.agents', 'rules');
    case 'cursor':
      return path.join(projectPath, '.cursor', 'rules');
    case 'claude-code':
    default:
      return path.join(projectPath, '.claude', 'rules');
  }
}

async function ensureDir(dirPath: string): Promise<void> {
  try {
    await vscode.workspace.fs.createDirectory(vscode.Uri.file(dirPath));
  } catch {
    // already exists
  }
}

/**
 * Regenerate the skills index file at `{skillsDir}/SKILL.md`.
 * The index lists every installed skill with its title, when-to-use guidance,
 * and location — so an AI agent can discover the right skill without scanning
 * every subfolder.
 */
export async function generateSkillsIndex(
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const skillsDir = getSkillsDir(projectPath, platform);
  const indexPath = path.join(skillsDir, 'SKILL.md');

  let entries: [string, vscode.FileType][];
  try {
    entries = await vscode.workspace.fs.readDirectory(vscode.Uri.file(skillsDir));
  } catch {
    return;
  }

  const skillFolders = entries.filter(([, type]) => type === vscode.FileType.Directory);

  if (skillFolders.length === 0) {
    try {
      await vscode.workspace.fs.delete(vscode.Uri.file(indexPath));
    } catch {
      // not present
    }
    return;
  }

  const items: { name: string; description: string; location: string }[] = [];

  for (const [folderName] of skillFolders) {
    const folderPath = path.join(skillsDir, folderName);
    let subEntries: [string, vscode.FileType][];
    try {
      subEntries = await vscode.workspace.fs.readDirectory(vscode.Uri.file(folderPath));
    } catch {
      continue;
    }

    const mdFiles = subEntries
      .filter(([n, t]) => t === vscode.FileType.File && n.toLowerCase().endsWith('.md'))
      .map(([n]) => n);
    if (mdFiles.length === 0) continue;

    const primary =
      mdFiles.find(n => n.toUpperCase() === 'SKILL.MD') ||
      mdFiles.find(n => n.toLowerCase() === `${folderName.toLowerCase()}.md`) ||
      mdFiles.find(n => n.toUpperCase() !== 'README.MD') ||
      mdFiles[0];

    let name = folderName;
    let description = '';
    try {
      const bytes = await vscode.workspace.fs.readFile(
        vscode.Uri.file(path.join(folderPath, primary)),
      );
      const content = Buffer.from(bytes).toString('utf-8');
      const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
      if (match) {
        for (const line of match[1].split(/\r?\n/)) {
          const idx = line.indexOf(':');
          if (idx === -1) continue;
          const key = line.slice(0, idx).trim();
          let value = line.slice(idx + 1).trim();
          if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
          if (key === 'name') name = value;
          else if (key === 'description') description = value;
        }
      }
    } catch {
      // unreadable — use folder name only
    }

    items.push({
      name,
      description,
      location: `./${folderName}/${primary}`,
    });
  }

  items.sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    '# Skills Index',
    '',
    'Quick reference for every skill installed in this workspace. Each skill lives in its own folder under this directory.',
    '',
    '## How to use',
    '',
    'When a task calls for a specific capability, consult this index first to find the right skill instead of scanning every folder. Open the referenced file to read the full skill definition.',
    '',
    '## Available skills',
    '',
  ];

  for (const item of items) {
    lines.push(`### ${item.name}`);
    if (item.description) {
      lines.push(`- **When to use:** ${item.description}`);
    }
    lines.push(`- **Location:** \`${item.location}\``);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `_Total: ${items.length} skill${items.length === 1 ? '' : 's'}. Auto-generated by Lazy Skill AI Agent — do not edit manually._`,
  );
  lines.push('');

  await vscode.workspace.fs.writeFile(
    vscode.Uri.file(indexPath),
    Buffer.from(lines.join('\n'), 'utf-8'),
  );
}

// --- Skills ---

export async function installSkill(
  skill: SkillInfo,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const skillsDir = getSkillsDir(projectPath, platform);
  await ensureDir(skillsDir);

  const sourceDir = path.dirname(skill.sourcePath);
  const targetDir = path.join(skillsDir, skill.name);

  try {
    await vscode.workspace.fs.delete(vscode.Uri.file(targetDir), {
      recursive: true,
      useTrash: false,
    });
  } catch {
    // not present
  }

  await vscode.workspace.fs.copy(
    vscode.Uri.file(sourceDir),
    vscode.Uri.file(targetDir),
    { overwrite: true },
  );
}

export async function uninstallSkill(
  skillName: string,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const targetDir = path.join(getSkillsDir(projectPath, platform), skillName);
  try {
    await vscode.workspace.fs.delete(vscode.Uri.file(targetDir), {
      recursive: true,
      useTrash: false,
    });
  } catch {
    // doesn't exist
  }
}

// --- Rules ---

export async function installRule(
  rule: RuleInfo,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const rulesDir = getRulesDir(projectPath, platform);
  await ensureDir(rulesDir);

  const ext = path.extname(rule.sourcePath) || '.md';
  const targetFile = path.join(rulesDir, `${rule.name}${ext}`);

  await vscode.workspace.fs.copy(
    vscode.Uri.file(rule.sourcePath),
    vscode.Uri.file(targetFile),
    { overwrite: true },
  );
}

export async function uninstallRule(
  ruleName: string,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const rulesDir = getRulesDir(projectPath, platform);
  // Try common rule extensions
  for (const ext of ['.md', '.mdc', '.txt']) {
    const target = path.join(rulesDir, `${ruleName}${ext}`);
    try {
      await vscode.workspace.fs.delete(vscode.Uri.file(target), { useTrash: false });
    } catch {
      // not present, try next
    }
  }
}

// --- Apply ---

export interface ApplyResult {
  skillsInstalled: number;
  skillsRemoved: number;
  rulesInstalled: number;
  rulesRemoved: number;
  errors: string[];
}

export async function applyChanges(
  allSkills: SkillInfo[],
  selectedSkillIds: Set<string>,
  allRules: RuleInfo[],
  selectedRuleIds: Set<string>,
  projectPath: string,
  platform: TargetPlatform,
): Promise<ApplyResult> {
  const result: ApplyResult = {
    skillsInstalled: 0,
    skillsRemoved: 0,
    rulesInstalled: 0,
    rulesRemoved: 0,
    errors: [],
  };

  for (const skill of allSkills) {
    const shouldInstall = selectedSkillIds.has(skill.id);
    if (shouldInstall && !skill.isInstalled) {
      try {
        await installSkill(skill, projectPath, platform);
        result.skillsInstalled++;
      } catch (e) {
        result.errors.push(`Skill ${skill.name}: ${e}`);
      }
    } else if (!shouldInstall && skill.isInstalled) {
      try {
        await uninstallSkill(skill.name, projectPath, platform);
        result.skillsRemoved++;
      } catch (e) {
        result.errors.push(`Skill ${skill.name}: ${e}`);
      }
    }
  }

  for (const rule of allRules) {
    const shouldInstall = selectedRuleIds.has(rule.id);
    if (shouldInstall && !rule.isInstalled) {
      try {
        await installRule(rule, projectPath, platform);
        result.rulesInstalled++;
      } catch (e) {
        result.errors.push(`Rule ${rule.name}: ${e}`);
      }
    } else if (!shouldInstall && rule.isInstalled) {
      try {
        await uninstallRule(rule.name, projectPath, platform);
        result.rulesRemoved++;
      } catch (e) {
        result.errors.push(`Rule ${rule.name}: ${e}`);
      }
    }
  }

  // Regenerate the skills index so AI agents can discover installed skills quickly
  try {
    await generateSkillsIndex(projectPath, platform);
  } catch (e) {
    result.errors.push(`Skills index: ${e}`);
  }

  return result;
}
